### ISSUE TITLE
Additional margins when nesting Grid Layout-Cards within Grid View Layouts

### ISSUE THREAD

**Issue by Jpsy** [thomasloven/lovelace-layout-card#137]
My Home Assistant version: core-2021.3.4

Layout-card version (FROM BROWSER CONSOLE): 2.2.3

What I am doing:
Nesting Layout-Cards of type grid within View Layouts of type grid.

What I expected to happen:
The margins of nested layout-cards should align with the margins of normal cards in the grid layout.

What happened instead:
1. Nested layout-cards have a left and right margin of 4px:

![image](https://user-images.githubusercontent.com/1806058/113760326-5ff68c00-9716-11eb-9bc3-8ecb064dc076.png)

2. If the nested layout-card is the very first card in a grid, it additionally gets an unwanted top-margin of 4px:

![image](https://user-images.githubusercontent.com/1806058/113760295-5836e780-9716-11eb-9b20-9e4363c13d57.png)

**Minimal** steps to reproduce:
This is a YAML block  for a complete Lovelace view as shown in the screenshots above. It can be pasted into Lovelace in raw edit mode.

```yaml
  - title: Grid Test
    path: grid-test
    type: 'custom:grid-layout'
    layout:
      grid-template-columns: 1fr 1fr 1fr
    badges: []
    cards:
      - &ref_0
        type: 'custom:layout-card'
        layout_type: grid
        cards:
          - type: button
            tap_action:
              action: toggle
            entity: light.couch
          - type: button
            tap_action:
              action: toggle
            entity: light.couch
        layout_options:
          grid-template-columns: 1fr 1fr
      - type: button
        tap_action:
          action: toggle
        entity: light.couch
      - type: button
        tap_action:
          action: toggle
        entity: light.couch
      - type: button
        tap_action:
          action: toggle
        entity: light.couch
      - *ref_0
      - type: button
        tap_action:
          action: toggle
        entity: light.couch
```

Error messages from the browser console:

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by mtandrup** [comment]
I can confim this issue as I am experiencing the exact same behaviour.

**Comment by AdrinkBeer** [comment]
Hey!

Did you find a workaround for this ?

**Comment by Jpsy** [comment]
Nope. Unfortunately not.

**Comment by jelgblad** [comment]
An option to disable the margins on `layout_type: grid` completely would be wonderful.

Something like this:
```yaml
type: custom:layout-card
layout_type: grid
container_margins: false
cards: []
```

In addition to solve this particular issue, it would also help with aligning this custom grid with the default grid-card which doesn't add any margins.

Here's the code where the margins gets added to `#root`:
https://github.com/thomasloven/lovelace-layout-card/blob/b146132f829cb616d9228958098e4b2f3d7f7ecb/src/layouts/grid.ts#L130-L131

**Comment by elahd** [comment]
#161 should help here -- can anyone test to confirm? To test:

1. Replace your own layout-card.js with [this version](https://github.com/thomasloven/lovelace-layout-card/blob/c980c5edb7997e44d2926b227c78b5a5736a8362/layout-card.js). On my system, this file is in `/config/www/community/lovelace-layout-card`. Yours should be in a similar location.
2. Modify your grid layout's config using yaml in the below format:
```yaml
style:
  margin: 0
```
`margin` accept values in the standard CSS `margin` shorthand, e.g.: `margin: 0px 10px 2px 5px`.

In context, it'll look something like this:
```yaml
title: Grid layout
type: custom:grid-layout
style:
  margin: 0
layout:
  grid-template-columns: auto 30px 25%
  grid-template-rows: auto
cards:
  - type: entities
    entities:
      - entity: light.bed_light
    view_layout:
      grid-area: header
```
3. In Home Assistant, go to Developer Tools → Services and call the "Home Assistant Frontend: Reload themes" service.
4. Clear your browser's cache.
5. Refresh page & check margins.

**Comment by davidmerrique** [comment]
@elahd Should this be padding instead? 

Typically with CSS grid, you would use padding to add space around the grid container. (Or at least that's what I do)

Either way 👍🏽

**Comment by elahd** [comment]
@davidmerrique I was working off of the existing styles, but more options can't hurt! I added support for configurable padding to the same PR. See the updated layout-card.js [here](https://github.com/thomasloven/lovelace-layout-card/blob/ec107531a2095d0e53e356b40954f14284a037cc/layout-card.js).

You can now do:

```yaml
style:
  margin: 0
  padding: 4px
```

**Comment by thomasloven** [comment]
I think this can be solved with the new layout options `margin`, `padding` and `card_margin`.

**Comment by Jpsy** [comment]
Great news, thanks!
I will check and report back here as soon as HA 2022.3 is released. 
(Sorry, can't run betas. Have to keep things stable or family will kill HA admin == me.)

**Comment by thomasloven** [comment]
If you don't rely on the GUI editors the latest version will work with 22.2 too, but you'll have to install it manually.

**Comment by u8915055** [comment]
I am having a similar problem here i believe.  I have a grid layout and then a grid layout card within that layout.  I am finding the margin, padding, and card_margin configuration options not having any effect.  Here is my config.

This my view configuration. i have a left hand side dashboard and the rest of the viewport for the second column.
```
  - type: custom:grid-layout
    path: '2'
    title: '2'
    layout:
      grid-template-columns: 384px 1fr
      grid-template-rows: auto
      grid-template-areas: |
        "footer   rooms"
        "sidebar  rooms"
        ".        rooms"
      mediaquery:
         #phone
        "(max-width: 915px)":
          grid-template-columns: 384px
          grid-template-areas: |
            "footer"
            "sidebar"
            "rooms"
    cards:
```

Then this is my layout card to put another grid in that right hand 1fr column.

```
      - type: custom:layout-card
        view_layout:
          grid-area: rooms
        layout_type: grid
        layout:
          grid-template-columns: 475px 475px 475px
          grid-template-rows: auto
          margin: 0
          padding: 0
          card_margin: 0
          mediaquery:
            "(max-width: 915px)":
              grid-template-columns: 384px
            "(max-width: 1385px)":
              grid-template-columns: 475px
            "(max-width: 1860px)":
              grid-template-columns: 475px 475px
        cards: 

        - type: custom:decluttering-card
          template: sonos_declutter
          variables:
            - entity: media_player.denise_office
```

There are a bunch of other cards there in that grid layout.  But for some reason i cannot get rid of margins for example.

**Comment by Jpsy** [comment]
@u8915055: 
Multiple problems with your config:
1. To get rid of all margins/paddings you must set `margin`/`padding`/`card_margin` not only in the grid card configs, but also in the view config.
2. The layout_type for the grid cards has changed from `grid` to `layout_type: custom:grid-layout`.

Here is a working **view config**:
```
  - title: Grid Test NEW
    path: grid-test-new
    type: custom:grid-layout
    layout:
      grid-template-columns: 1fr 1fr
      margin: 0
      padding: 0
      card_margin: 0
```
This is taken from the raw editor. You get this through these settings in the view's UI editor:

![image](https://user-images.githubusercontent.com/1806058/157607728-000cf44a-2cbc-4c06-8fa1-ca7bd1d50bfd.png)

And here is a working **card config**:
```
type: custom:layout-card
layout_type: custom:grid-layout
cards:
  - type: button
    tap_action:
      action: toggle
    entity: light.couch
  - type: button
    tap_action:
      action: toggle
    entity: light.couch
layout:
  grid-template-columns: 1fr 1fr
  margin: 0
  padding: 0
  card_margin: 0
```
UI-Editor:
![image](https://user-images.githubusercontent.com/1806058/157607814-11c217f8-c6b9-4c37-8c9b-c3fa1c293acc.png)

All this being said, some margins can be eliminated with the new properties, but not all of them.
I will come to this in my next posting.

**Comment by thomasloven** [comment]
Remember that css `margin` can be a negative number too.

**Comment by Jpsy** [comment]
Hi @thomasloven, 
you are right, negative margins can resolve nearly all issues.

But there is one problem left. I already mentionen that in my original issue report. But let me isolate it again:

If you use grid layout cards nested within a grid layout, the very first card has a top-margin that differs from all other cards.

The following example is a grid view. Each row has a grid layout card with 2 inner button cards (the small buttons), followed by a stand-alone normal button card (the big button).

![image](https://user-images.githubusercontent.com/1806058/158027101-a95af9ea-f12a-4012-bf6b-1bea6cf648db.png)

 

As you can see, the small buttons in the first row do not top-align with the big button (4px difference), while in the second row they align perfectly.
The reason for that is the following constructed stylesheet that is attached to all `<layout-card>`s:

![image](https://user-images.githubusercontent.com/1806058/158027334-950fe319-a6a7-4665-b024-5d001dd8ee1e.png)

It zeroes out the top-margins of all cards in the view but the very first card. The very first card keeps it standard `top-margin: 4px`.

Sure, I could compensate this by giving that first card other margins than all following cards.
But if I use grid-areas in my view (which I do often because it is a major advantage of grids) these areas can change their position and their order with different screen resolutions.  The card which is the very first now may not be the first on a mobile.

Is it possible to remove this different handling? I don't care if all cards have 0 top-margin or 4px top-margin, as long as they are all the same.
I guess this different handling is actually a remnant of non-grid views. But it does not really make sense in grid views.

Here is a YAML block for a complete Lovelace view to reproduce the above screen shot. It can be pasted into Lovelace in raw edit mode.

```
  - title: Grid Test NEW
    path: grid-test-new
    type: custom:grid-layout
    layout:
      grid-template-columns: 1fr 1fr
      margin: 0
      padding: 0
      card_margin: 0
    badges: []
    cards:
      - type: custom:layout-card
        layout_type: custom:grid-layout
        cards:
          - type: button
            tap_action:
              action: toggle
            entity: light.couch
          - type: button
            tap_action:
              action: toggle
            entity: light.couch
        layout:
          grid-template-columns: 1fr 1fr
          margin: 0 -4px 0 -4px
          padding: 0
          card_margin: 0
      - type: button
        tap_action:
          action: toggle
        entity: light.couch
      - type: custom:layout-card
        layout_type: custom:grid-layout
        cards:
          - type: button
            tap_action:
              action: toggle
            entity: light.couch
          - type: button
            tap_action:
              action: toggle
            entity: light.couch
        layout:
          grid-template-columns: 1fr 1fr
          margin: 0 -4px 0 -4px
          padding: 0
          card_margin: 0
      - type: button
        tap_action:
          action: toggle
        entity: light.couch
```

Oh. And one more time: Thanks for all your great Lovelace cards. 
My HA dashboards would not be possible without them!

**Comment by andrewjswan** [comment]
Same problem, could not override the margin values in #root > * can there be any solution?
![image](https://user-images.githubusercontent.com/3609660/173771688-a2005f7a-cad8-44b4-bc54-7f9e76140cd6.png)

**Comment by emufan** [comment]
Same here. I played around a lot for having card_margin set in grid layout. But nothing is working. Would appreciate any help.

**Comment by snairolf** [comment]
Same here. `card_mod` seems to be a no-op.

**Comment by prs-wjy** [comment]
same problem, is there any solution for it yet? i can't find any solution :(

**Comment by m-klecka** [comment]
Also have this problem, margins at sides and bottom when using custom-grid card. Can be solved by setting negative margins, but thats stupid when you have lot of cards.

**Comment by aaamoeder** [comment]
having the same issue .. driving my odd self nuts...

**Comment by EmJay276** [comment]
I have the same issue 😢

**Comment by matteobrusa** [comment]
same here, card_margin seems to have no effect.

**Comment by mrestorff** [comment]
For anyone wondering what exact negative margins have to be used: I solved this by using `margin: "-4px -4px 0px -4px"` in the `layout_options`, which is applied to the `grid-layout` element. This negates the 4px applied by the `layout-card` element.

While this is a good workaround, having layout-card detect when it's nested inside another one and apply the fix itself would be even better. Is there any way of implementing that level of self-awareness without too much effort?

**Comment by zholdak** [comment]
Nothing works anyway. Unwanted margins remains. No any hope to be fixed since Apr 6, 2021...

**Comment by hmax-72** [comment]
> Remember that css `margin` can be a negative number too.

you're right: Setting margin to -4px did it.

```
- type: custom:layout-card
            layout_type: custom:grid-layout
            layout:
              grid-template-columns: 50% auto 25%
              grid-template-rows: auto
              grid-template-areas: |
                "left middle right"
              place-items: stretch stretch
              margin: -4px
            cards:
              - type: custom:mushroom-vacuum-card
```

**Comment by tbarbette** [comment]
Any solution by now? :) Negative margin does not work :(

**Comment by Lx** [comment]
From [the README as currently published](https://github.com/thomasloven/lovelace-layout-card/blob/b63bf93daf166609ededbafc7b31a6e5d88037c3/README.md#layouts):

> All column based layouts accept the following layout options:
> ...
> `card_margin`

I think all we need is for `card_margin` to be honoured by `custom:grid-layout` too.  Currently it's defined in the `BaseColumnLayout` class:

https://github.com/thomasloven/lovelace-layout-card/blob/b63bf93daf166609ededbafc7b31a6e5d88037c3/src/layouts/base-column-layout.ts#L96

...but not the `GridLayout` class:

https://github.com/thomasloven/lovelace-layout-card/blob/b63bf93daf166609ededbafc7b31a6e5d88037c3/src/layouts/grid.ts#L54-L62

@thomasloven, can you foresee a problem with `card_margin` processing logic being either:
- copied from the `BaseColumnLayout` class to the `GridLayout` class; or
- moved to `BaseLayout`?

**Comment by Dutchstyler** [comment]
Have I think the same problem. What ever I try, card_margin looks not working. The normal margin and padding does works.

**Comment by Phobos-7** [comment]
This is what worked for me (example):
```

grid-template-columns: 35% 45% 20%
grid-template-rows: auto
width: 160
max_cols: 3
margin: -4px

```

**Comment by daha76** [comment]
I am fighting the same issue, for now, I fixed it like many others with a negative margin of -4px.

**Comment by Montreal666** [comment]
Fixed it by embedding everything in mod-card:

```
type: custom:mod-card
card_mod:
  style:
    layout-card$:
      grid-layout$: |
        :host {
          padding: 0px !important;
        }
        #root {
          margin: 0px !important;
        }
        #root > * {
          margin: 0.1rem !important;
        }
card:
  type: custom:layout-card
  layout_type: grid
  layout:
    grid-template-columns: 30% 30% 1fr
    grid-template-rows: auto
    grid-template-areas: |
      "A A1 A2"
      "A A1 B2"
  cards:
```

but having a working option directly under layout-card would be much simpler as this doesn't work here:

```
        layout:
          margin: 0
          padding: 0
          card_margin: 0
```

**Comment by TarcisioMenezes** [comment]
`card_margin` doesn't seem to be working for me either...

```
- type: custom:layout-card
  layout_type: custom:grid-layout
  layout:
    card_margin: '100px 100px 100px'
    padding: 0px
    grid-template-columns: 25% 25% 25% 25%
    grid-template-rows: auto
    grid-template-areas: |
      "1 1 1 2"
```
tested with 100px just to have a visual reference of the card moving if it was working. Nothing happens though ...
`margin` and `padding` work.

**Comment by efaden** [comment]
Struggling with this also.  I'm using the bubble card popups and between using the grid-layout view and the bubble card popups I have a bunch of blank space at the bottom.

**Comment by lisz8** [comment]
Another way to kill gaps inside layout-card is to use card_mod on each element E.g.:
```
type: custom:layout-card
layout_type: custom:grid-layout
layout:
  margin: 0
  grid-gap: 0 0
  grid-template-columns: 1fr 1fr
  grid-template-rows: auto
cards:
  - type: custom:button-card
    name: Green
    styles:
      card:
        - background: green
        - border-radius: 0
    card_mod:
      style: |
        :host {
          --masonry-view-card-margin: 0px;
        }
  - type: custom:button-card
    name: Blue
    styles:
      card:
        - background: blue
        - border-radius: 0
        - color: white
    card_mod:
      style: |
        :host {
          --masonry-view-card-margin: 0px;
        }
  - type: custom:button-card
    name: Brown
    styles:
      card:
        - background: brown
        - border-radius: 0
    card_mod:
      style: |
        :host {
          --masonry-view-card-margin: 0px;
        }
  - type: custom:button-card
    name: Orange
    styles:
      card:
        - background: orange
        - border-radius: 0
    card_mod:
      style: |
        :host {
          --masonry-view-card-margin: 0px;
        }
```
Result:
![obraz](https://github.com/user-attachments/assets/0653e9fe-b7fb-42fa-a797-446b30233ec2)

Then you can cotroll the gaps with "grid-gap", and whole card's margin by "layout -> margin" (also negative).

**Comment by jwdinker** [comment]
For all the folks that still get frustrated with this see below.  Since a `margin` prop still doesn't exist when using the `grid-layout` of `custom:layout-card`, card-mod provides the cleanest solution to nuke all the margins.  For my particular use case I was adding a row of buttons to a panel dashboard.
```yaml  
- type: panel
  cards: 
    - type: picture-elements:
       elements:
          ...
          - type:
          - type:
          - type: custom:layout-card
            layout_type: custom:grid-layout
            card_mod:
              style: |
                grid-layout {
                  --masonry-view-card-margin: 0px; 
                  --layout-margin: 0px;
                }
```

The red is the container without the card-mod settings.  When the card-mod is added, the margin disappears.
![2025-01-10_17-15-44 (2)](https://github.com/user-attachments/assets/d9911997-47df-43a4-bc6b-d5865778be3d)

**Comment by perlchamp** [comment]
@jwdinker :
unbelievable, wow (cause of the readme of card-mod) :

> NOTE: card-mod only works on cards that contain a ha-card element. This includes almost every card which can be seen, but not e.g. conditional, entity_filter, vertical-stack, horizontal-stack, grid.

Maybe you've done some margin-settings in your picture card.

margin in the layout-option makes the difference:

![Image](https://github.com/user-attachments/assets/93e28c9e-02a6-490a-99cc-30728c3c4359)

the code:
```
views:
  - title: WG 4
    type: custom:layout-card
    layout_type: custom:grid-layout
    config:
      show_side_bar: false
      show_app_header: false
    layout:
      grid-template-columns: auto 390px
      grid-template-rows: 35px max-content 25px
    cards:
      - type: custom:layout-card
        layout_type: custom:horizontal-layout
        layout:
          margin: '-4px 0px 0px -4px'
          padding: 0
          max_cols: 30
          width: 27
        view_layout:
          grid-area: 1 / 1 / 2 / 2
        cards:
          - type: custom:button-card
            show_entity_picture: true
            entity_picture: /local/img/button/dg-logo.svg
            tap_action:
              action: navigate
              navigation_path: /dashboard-grundriss/0
            styles:
              card:
                - border-radius: 0px;
                - background-color: rgb(50,50,50);
                - max-height: 30px;
                - width: 27px;
                - min-width: 27px;
                - max-width: 27px;
                - padding: 0px;
                - margin: 0px;
                - border: 1px solid orange;
              entity_picture:
                - width: 25px;
      - type: custom:floorplan-card
        title: Grundriss
        show_header_toggle: true
        card_mod:
          style: |
            ha-card {
              border-radius: 0px;
              padding: 0px;
              margin: 0px;
            }
        view_layout:
          grid-area: 2 / 1 / 3 / 2
      - type: custom:layout-card
        layout_type: custom:vertical-layout
        view_layout:
          grid-area: 1 / 2 / 4 / 3
        layout:
          margin: '-8px 0px 0px -2px'
        cards:
          - type: custom:layout-card
            layout_type: custom:horizontal-layout
            layout:
              width: 188
              padding: 0
              margin: '-4px 0px 0px 4px'
            title: BB und ND
            cards:
              - type: custom:html-template-card
                title: BB
                ignore_line_breaks: true
                content: |
                  BB
              - type: custom:html-template-card
                title: ND
                ignore_line_breaks: true
                content: |
                  <style>
                    ha-card {
                      height: 188px;
                      max-height: 188px;
                      min-height: 188px;
                      width: 188px;
                      max-width: 188px;
                      min-width: 188px;
                      border: 1px solid blue;
                      border-radius: 0px;
                      padding: 0px;
                      margin: 0px 0px 0px 0px;
                    }            
                  </style>
                  ND
          - type: custom:layout-card
            layout_type: custom:horizontal-layout
            layout:
              width: 188
              padding: 0
              margin: '-10px 0px 0px 4px'
            title: ES und GT
            cards:
              - type: custom:html-template-card
                title: ES
                ignore_line_breaks: true
                content: |
                  ES
              - type: custom:html-template-card
                title: GT
                ignore_line_breaks: true
                content: |
                  <style>
                    ha-card {
                      height: 188px;
                      max-height: 188px;
                      min-height: 188px;
                      width: 188px;
                      max-width: 188px;
                      min-width: 188px;
                      border: 1px solid yellow;
                      border-radius: 0px;
                      padding: 0px;
                      margin: 0px 0px 0px 0px;
                    }
                  </style>
                  GT
          - type: custom:html-template-card
            title: GC
            ignore_line_breaks: true
            content: |
              <style>
                    ha-card {
                      height: 376px;
                      max-height: 376px;
                      min-height: 376px;
                      width: 376px;
                      max-width: 376px;
                      min-width: 376px;
                      border: 1px solid red;
                      border-radius: 0px;
                      margin: -10px 0px 0px 6px;                     
                      padding: 0px;
                    }
              </style>
              GC
```

If somebody could figure out, how to get the button (square, top-line) from the centered positon to the left or right side by USING the custom:HORIZONTAL-LAYOUT , than please contact me.
Many thanks in advance!

So long
Pc

**Comment by Forsskieken** [comment]
Hi there,

I was struggling with this to and when I found the --masonry-view-card-margin: 8px with the help of F12. I asked my new AI friends.. I have 3 now but they didn't really help me.  
Luckily you where here.
This is my testing for a NON nested layout card:

```
views:
  - path: default_view
    title: Home
    type: panel
    cards:
      - type: custom:layout-card
        layout_type: custom:grid-layout
        layout:
          gap: 0

          padding: 0
          card_margin: 0
          grid-template-columns: repeat(6, 91.5px)
          grid-template-rows: auto
          grid-template-areas: |
            "plaats1 plaats2 plaats3 plaats4 plaats5 plaats6"
            "plaats7 plaats8 plaats9 plaats10 plaats11 plaats12"
          mediaquery:
            '(max-width: 415px)':
              gap: 0
              margin: 0
              padding: 0
              card_margin: 0px
              grid-template-columns: repeat(1, 100%)
              grid-template-rows: auto
              grid-template-areas: |
                "plaats1"
                "plaats2"
                "plaats3"
                "plaats4"
                "plaats5"
                "plaats6"
            '(max-width: 920px)':
              gap: 0
              margin: 0
              padding: 0
              card_margin: 0px
              grid-template-columns: repeat(3, 91.5px)
              grid-template-rows: auto
              grid-template-areas: |
                "plaats1 plaats2 plaats3"
                "plaats4 plaats5 plaats6"
                "plaats7 plaats8 plaats9"                
            '(max-width: 1400px)':
              gap: 0
              margin: 0
              padding: 0
              card_margin: 0px
              grid-template-columns: repeat(4, 91.5px)
              grid-template-rows: auto
              grid-template-areas: |
                "plaats1 plaats2 plaats3 plaats4"
                "plaats5 plaats6 plaats7 plaats8"
                "plaats9 plaats10 plaats11 plaats12"
            '(max-width: 2100px)':
              gap: 0
              margin: 0
              padding: 0
              card_margin: 0px
              grid-template-columns: repeat(6, 91.5px)
              grid-template-rows: auto
              grid-template-areas: >
                "plaats1 plaats2 plaats3 plaats4 plaats5 plaats6" "plaats7
                plaats8 plaats9 plaats10 plaats11 plaats12"                
        cards:
          - type: markdown
            content: |
              <div style="line-height: 1; margin: 0; padding: 0;">1</div>
            view_layout:
              grid-area: plaats1
            card_mod: &ref_0
              style: |
                :host {
                  --masonry-view-card-margin: 0px;
                }
                ha-card {
                  height: 113.3px !important;
                  width: 91.5px !important;
                  border: 6px solid black !important;
                  display: flex !important;
                  justify-content: center !important;
                  align-items: center !important;
                  padding: 0 !important;
                  margin: 0 !important;
                  font-size: 36px !important;
                  font-weight: bold !important;
                  overflow: hidden !important;
                  card_margin: 0px
                }                
          - type: markdown
            content: |
              <div style="line-height: 1; margin: 0; padding: 0;">2</div>
            view_layout:
              grid-area: plaats2
            card_mod: *ref_0
          - type: markdown
            content: |
              <div style="line-height: 1; margin: 0; padding: 0;">3</div>
            view_layout:
              grid-area: plaats3
            card_mod: *ref_0
          - type: markdown
            content: |
              <div style="line-height: 1; margin: 0; padding: 0;">4</div>
            view_layout:
              grid-area: plaats4
            card_mod: *ref_0
          - type: markdown
            content: |
              <div style="line-height: 1; margin: 0; padding: 0;">5</div>
            view_layout:
              grid-area: plaats5
            card_mod: *ref_0
          - type: markdown
            content: |
              <div style="line-height: 1; margin: 0; padding: 0;">6</div>
            view_layout:
              grid-area: plaats6
            card_mod: *ref_0
          - type: picture
            image: /local/car/aimg7.png
            view_layout:
              grid-area: plaats7
            card_mod:
              style: |
                ha-card {
                  width: 91.5px;
                  height: 113.3px;
                  padding: 0;
                  border: none;
                  border-radius: 0;
                }
                :host {
                  --masonry-view-card-margin: 0px;
                }
                ha-card img {
                  display: block; /* <-- ADD THIS LINE */
                  width: 100%;
                  height: 100%;
                  object-fit: fill;
                }
          - type: picture
            image: /local/car/aimg8.png
            view_layout:
              grid-area: plaats8
            card_mod:
              style: |
                ha-card {
                  width: 91.5px;
                  height: 113.3px;
                  padding: 0;
                  border: none;
                  border-radius: 0;
                }
                :host {
                  --masonry-view-card-margin: 0px;
                }
                ha-card img {
                  display: block; /* <-- ADD THIS LINE */
                  width: 100%;
                  height: 100%;
                  object-fit: fill;
                }
          - type: picture
            image: /local/car/aimg9.png
            view_layout:
              grid-area: plaats9
            card_mod:
              style: |
                ha-card {
                  width: 91.5px;
                  height: 113.3px;
                  padding: 0;
                  border: none;
                  border-radius: 0;
                }
                :host {
                  --masonry-view-card-margin: 0px;
                }
                ha-card img {
                  display: block; /* <-- ADD THIS LINE */
                  width: 100%;
                  height: 100%;
                  object-fit: fill;
                }
          - type: picture
            image: /local/car/aimg10.png
            view_layout:
              grid-area: plaats10
            card_mod:
              style: |
                ha-card {
                  width: 91.5px;
                  height: 113.3px;
                  padding: 0;
                  border: none;
                  border-radius: 0;
                }
                :host {
                  --masonry-view-card-margin: 0px;
                }
                ha-card img {
                  display: block; /* <-- ADD THIS LINE */
                  width: 100%;
                  height: 100%;
                  object-fit: fill;
                }
          - type: picture
            image: /local/car/aimg11.png
            view_layout:
              grid-area: plaats11
            card_mod:
              style: |
                ha-card {
                  width: 91.5px;
                  height: 113.3px;
                  padding: 0;
                  border: none;
                  border-radius: 0;
                }
                :host {
                  --masonry-view-card-margin: 0px;
                }
                ha-card img {
                  display: block; /* <-- ADD THIS LINE */
                  width: 100%;
                  height: 100%;
                  object-fit: fill;
                }
          - type: picture
            image: /local/car/aimg12.png
            view_layout:
              grid-area: plaats12
            card_mod:
              style: |
                ha-card {
                  width: 91.5px;
                  height: 113.3px;
                  padding: 0;
                  border: none;
                  border-radius: 0;
                }
                :host {
                  --masonry-view-card-margin: 0px;
                }
                ha-card img {
                  display: block; /* <-- ADD THIS LINE */
                  width: 100%;
                  height: 100%;
                  object-fit: fill;
                }
```

<img width="91" height="113" alt="Image" src="https://github.com/user-attachments/assets/e3ae2521-b385-454c-ad39-95d84f608698" />
<img width="91" height="113" alt="Image" src="https://github.com/user-attachments/assets/817b82f9-9277-4611-853e-a1c3563dee9f" />
<img width="91" height="113" alt="Image" src="https://github.com/user-attachments/assets/e56d5f82-c3ff-4343-ad39-a80ffe1373b1" />
<img width="91" height="113" alt="Image" src="https://github.com/user-attachments/assets/bcd4c2e1-da57-4c88-9e94-f6bf5fd82df8" />
<img width="91" height="113" alt="Image" src="https://github.com/user-attachments/assets/8756463e-bea5-4294-83b9-fdb8a171b99f" />
<img width="91" height="113" alt="Image" src="https://github.com/user-attachments/assets/e89257c5-8019-4a35-954d-0ced2730d021" />

I also added the img you'll have to upload it to a /homeassistant/www/car
