### ISSUE TITLE
Only one column of cards is displayed

### ISSUE THREAD

**Issue by bieniu** [thomasloven/lovelace-layout-card#17]
Often (not always) only one column of cards is displayed when I switch between views. I must then refresh the page or turn on the HA sidebar for a moment or switch view so that the number of columns returns to normal. I have cleaned the browser cache many times. Any solution for that?

HA: 0.89.2
layout-card: 226f86
browser: Chrome/Opera/Firefox

Incorrect view with one column:

![image](https://user-images.githubusercontent.com/478555/54602288-8ec33c00-4a41-11e9-8fd0-db23cfcedbff.png)

My config:
```
title: 'Dom'
views:
  - id: home
    icon: mdi:home
    title: 'Pomieszczenia'
    background: '#e5e5e5 / center / cover no-repeat url("/local/pictures/bg.jpg") fixed'
    path: home
    panel: true
    cards:
      - type: custom:layout-card
        cards:
          - ...
          - ...
  - id: network
    icon: mdi:ethernet
    title: 'Sieć'
    background: '#e5e5e5 / center / cover no-repeat url("/local/pictures/bg.jpg") fixed'
    path: network
    panel: true
    cards:
      - type: custom:layout-card
        cards:
          - ...
          - ...

```

**Comment by thomasloven** [comment]
Do you have custom cards in your layout-cards? Card-modder, auto-entities?

**Comment by bieniu** [comment]
Yes, I have vertical-stack-in-card, tracker-card, mini-media-player, dark-sky-weather-card, monster-card and mini-graph-card. But this happens also on view where I don't have any custom cards (only layout-card).

**Comment by thomasloven** [comment]
I have experienced this problem too, but it's really really hard to debug.
I'll keep trying.
Please let me know if you come up with some consistent way of triggering it.

The new `rebuild:` parameter may help a bit, but not always as far as I can tell...

**Comment by bieniu** [comment]
What value to use for `rebuild`? I used 100 and it probably helped. Unfortunately, after the last update, the number of columns is changing strangely. There are only 4 columns without the `column_width` parameter (previously there were 5). With the` column_width: 320` parameter, I have 5 columns but when I open the side panel, the number of columns doesn't decrease, although the width of the columns is less than 320.

**Comment by thomasloven** [comment]
Enough so that all your card have time to load. I use 1000.

**Comment by thomasloven** [comment]
I think I have found a way to minimize the impact of this problem. Please let me know if the latest update works for you.

**Comment by bieniu** [comment]
After last update, I didn't had a single column issue. But still there is an issue with too many columns after turning on the side menu of HA. This issue appeared after the previous update.

There should be four columns after opening the side menu, and there are five columns.
![image](https://user-images.githubusercontent.com/478555/55511582-3a36d800-5661-11e9-8adb-ad22a88c9ed9.png)

**Comment by thomasloven** [comment]
Please try this with the latest version and let me know if there's still a problem.

**Comment by bieniu** [comment]
Fixed via latest version. Thanks.

**Comment by sanderjonkers** [comment]
I have the same issue of having only a single collumn after switching views. After a full browser refresh it shows the normal 3 collumns I have configured. I had this issue in version 6, and I have just updated to version 7, and the issue is still present.

I have this issue almost constantly on my wall mounted android tablet running lovelace in the Fully Kiosk browser, but I also have it sometimes using Firefox on a windows 10 laptop.

I have set the rebuild parameter to 1000, but I'm not sure if this would still function, as I can't find this parameter anymore in the readme.

I do use other custom cards within the layout cards BTW, like custom button card, mini-graph and mod-card.

**Comment by giacomocarrozzo** [comment]
Hi @thomasloven 
I have the same issue. When I change view all my cards are vertical stacked, I need to reload the page to fix it everytime.

**Comment by bieniu** [comment]
Issue returns with version 6 and 7.

**Comment by thomasloven** [comment]
Try 8

**Comment by bieniu** [comment]
Fixed via version 8.

**Comment by sanderjonkers** [comment]
I can confirm that it's fixed in version 8, at least for me. Thanks!

**Comment by bpraznik** [comment]
Seems that this is still and issue even with just the example implementation 
![image](https://user-images.githubusercontent.com/7223506/96963456-f5a3b380-1508-11eb-877b-2fd576d297f1.png)
![image](https://user-images.githubusercontent.com/7223506/96963510-0a804700-1509-11eb-9f1c-113dfb998e06.png)

**Comment by thomasloven** [comment]
No. Your problem is an entirely different one caused by not realizing that `layout-card` is a *card* with all that entails. See https://github.com/thomasloven/lovelace-layout-card#layouts
